language: node_js
node_js:
    - stable
branches:
    only:
    - master
script:
    - npm test
env:
    global:
    - GH_REPO: github.com/${TRAVIS_REPO_SLUG}
    - secure: VdsHKxUtsjiOecYE/ygsoqsbjYNGgkVWM18rzOTzJLkrN2tAkG9RAKZOCzMbvaF+KJDPLx6e70duWGZ0yWNBr9J65WJbC5J+0+6aYMNbtkl0By7TGvx5wZuw6sQja4yHTYbU/lFzFXhNtEcOtBByb4n4oa3JC5DhHfcd3OCiCc5OWcXNj3mYJYg3OoWbUoSQPM7eqXTwYgOpU3mewqhxO5ybp6gy8WCDL405TysK8oSvIUR1HYtHahRtUQsPHU3rGErHRHY/TMdhpaqvQ2EuEW7uH7+UvgZBWyJxBX3cja/H0TLmpcV6hUpY6c6DRDIvgAbL9n9aJlSxvzxd9FgzwS/ehUIYHrN+HcYWzmlgEIJYhl+ZNdfTQ4LeibHAPSOzDfghxGDbr8R1Y7OI97fOrDAFPxTVdGFAM+b287nQcGXQpL+/r8jF/ic8k6I4fGda/YuFuHkX/zGZRlRbI7dACvGk+QLJaTeCHei47kd2ABCy96F/q/Croc4g1XhDR/S819AjU6CoZ1XbHjDOg5x6cj8VmUW/GSYRXtIaFYMYlJNYoZcv04K47wCmGKMtXj32nUfLCtqBBZpF/QtVRn4v49Gh98sTuZ1H8XwRUWbzU+lv1IDtXsAVSBpk/m8N5+VlOpvdTmU2y037mq+2Ed6iDyFqlNNa6ojvDT9xxvhFiMo=
after_success:
    - npm run deploy
